# Generated by Django 2.1.2 on 2018-10-07 14:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mqtt_topic', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('mqtt_payload_on', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('mqtt_payload_off', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Action')),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mqtt_topic', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('action', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Action')),
                ('sensor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sunday', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('monday', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('tuesday', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('wednesday', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('thursday', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('friday', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('saturday', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('actionType', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ActionType')),
                ('weeklyProgram', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.WeeklyProgram')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensorType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.SensorType'),
        ),
        migrations.AddField(
            model_name='action',
            name='actionType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ActionType'),
        ),
    ]
